version: 2
jobs:
  build:
    docker:
      - image: thegreenhouse/nodejs-dev:0.3.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Project Dependencies
          command: yarn install

      - run:
          name: Run Linting
          command: yarn lint

      - run:
          name: Run Unit Tests
          command:  export CI_RUN=true && yarn test

      - run:
          name: Run Build
          command: yarn clean && yarn build
